# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=10)),
                ('start_time', models.FloatField()),
            ],
        ),
    ]
