# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='velocity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
