# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note_velocity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='note',
            name='start_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='note',
            name='velocity',
            field=models.IntegerField(default=0),
        ),
    ]
